name: Validate Kubernetes
on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform fmt -check -recursive
      - run: terraform init 
      - run: terraform validate
